### PR TITLE
Fix false positives

### PR DESCRIPTION
**Pull request by ergonlogic**
This PR merges a couple upstream commits, and adds a fix for https://www.drupal.org/node/2738069 (rerolled, due to the upstream commits).

### CODE REVIEW

**Comment by ergonlogic** [comment]
Hmm, I'd meant to do a separate PR for those last couple commits, but I forgot to start a feature branch. Sorry.

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
add to whitelist

**Comment by ergonlogic** [comment]
It looks like the tests have passed: https://ci.symbiotic.coop/job/hosting_civicrm/. By pushing to the same branch while the original testes were still running, might I have confused Jenkins?

**Comment by mlutfy** [comment]
I'm not too sure, but I confirm that the tests passed. Merged. Thanks!

**Pull request merged**
